apiVersion: v1
kind: Service
metadata:
  name: apache
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: apache
  ports:
    - protocol: TCP
      port: 80           # Port exposed inside the cluster
      targetPort: 80     # Port on the container
      nodePort: 30080    # Port exposed on the node (can be omitted to auto-assign)
